import type { Scheme } from "./schemes";

type Seed = Omit<Scheme, "source" | "createdAt" | "lastVerifiedAt">;

const docs = (en: string[], hi: string[]) => ({ en, hi });

// Starter catalogue, loaded into the database the first time it is created.
// AI discovery adds to this over time. Figures reflect publicly announced
// scheme rules; users are always sent to the official site to confirm.
export const SEED_SCHEMES: Seed[] = [
  {
    id: "pm-kisan", level: "central", stateKey: null,
    name: { en: "PM-KISAN Samman Nidhi", hi: "पीएम-किसान सम्मान निधि" },
    desc: { en: "Yearly cash support paid straight to farming families.", hi: "किसान परिवारों को हर साल सीधे मिलने वाली नकद सहायता।" },
    benefits: { en: "₹6,000 a year, sent as three instalments of ₹2,000 to the bank account.", hi: "साल में ₹6,000, ₹2,000 की तीन किस्तों में बैंक खाते में।" },
    eligibility: { en: "Families that own cultivable land. Income-tax payers, pensioners above the limit and government staff are left out.", hi: "खेती योग्य ज़मीन वाले परिवार। आयकरदाता, सीमा से ऊपर के पेंशनभोगी और सरकारी कर्मचारी शामिल नहीं।" },
    documents: docs(["Aadhaar", "Land ownership papers", "Bank account details"], ["आधार", "ज़मीन के कागज़", "बैंक खाते का विवरण"]),
    url: "https://pmkisan.gov.in", tags: ["central", "agriculture", "farmer", "rural", "income"],
    popularity: 98, year: 2019, criteria: { occupations: ["farmer"], minAge: 18 },
  },
  {
    id: "pmfby", level: "central", stateKey: null,
    name: { en: "Pradhan Mantri Fasal Bima Yojana", hi: "प्रधानमंत्री फसल बीमा योजना" },
    desc: { en: "Insurance that pays out when crops are lost to weather, pests or disease.", hi: "मौसम, कीट या बीमारी से फसल खराब होने पर भुगतान करने वाला बीमा।" },
    benefits: { en: "Claim for crop loss; the farmer pays only 1.5%–5% of the premium.", hi: "फसल नुकसान पर दावा; किसान को प्रीमियम का केवल 1.5%–5% देना होता है।" },
    eligibility: { en: "Any farmer growing a notified crop in a notified area, including tenants and sharecroppers.", hi: "अधिसूचित क्षेत्र में अधिसूचित फसल उगाने वाला कोई भी किसान, किरायेदार और बटाईदार भी।" },
    documents: docs(["Aadhaar", "Land record or tenancy agreement", "Sowing declaration", "Bank passbook"], ["आधार", "भूमि रिकॉर्ड या किरायानामा", "बुवाई घोषणा", "बैंक पासबुक"]),
    url: "https://pmfby.gov.in", tags: ["central", "agriculture", "farmer", "insurance", "rural"],
    popularity: 88, year: 2016, criteria: { occupations: ["farmer"], minAge: 18 },
  },
  {
    id: "kcc", level: "central", stateKey: null,
    name: { en: "Kisan Credit Card", hi: "किसान क्रेडिट कार्ड" },
    desc: { en: "Cheap working-capital credit for crops, dairy, poultry and fishing.", hi: "फसल, डेयरी, मुर्गी पालन और मछली पालन के लिए सस्ता ऋण।" },
    benefits: { en: "Loans up to ₹3 lakh with an effective rate near 4% when repaid on time.", hi: "समय पर चुकाने पर लगभग 4% प्रभावी ब्याज पर ₹3 लाख तक ऋण।" },
    eligibility: { en: "Owner and tenant farmers, sharecroppers, fishers, animal keepers and farmer self-help groups.", hi: "मालिक और किरायेदार किसान, बटाईदार, मछुआरे, पशुपालक और किसान स्वयं सहायता समूह।" },
    documents: docs(["Aadhaar", "Land records", "Photograph"], ["आधार", "भूमि रिकॉर्ड", "फोटो"]),
    url: "https://www.myscheme.gov.in/schemes/kcc", tags: ["central", "agriculture", "farmer", "business", "rural"],
    popularity: 85, year: 1998, criteria: { occupations: ["farmer"], minAge: 18 },
  },
  {
    id: "ayushman-bharat", level: "central", stateKey: null,
    name: { en: "Ayushman Bharat PM-JAY", hi: "आयुष्मान भारत पीएम-जय" },
    desc: { en: "Free hospital treatment for poorer families and all people aged 70+.", hi: "गरीब परिवारों और 70+ आयु के सभी लोगों के लिए मुफ़्त अस्पताल इलाज।" },
    benefits: { en: "Cashless cover up to ₹5 lakh per family per year at listed hospitals.", hi: "सूचीबद्ध अस्पतालों में प्रति परिवार प्रति वर्ष ₹5 लाख तक कैशलेस इलाज।" },
    eligibility: { en: "Families identified in the SECC deprivation list, and every citizen aged 70 or older.", hi: "SECC वंचना सूची में शामिल परिवार, और 70 वर्ष या उससे अधिक आयु का हर नागरिक।" },
    documents: docs(["Aadhaar", "Ration card", "Mobile number"], ["आधार", "राशन कार्ड", "मोबाइल नंबर"]),
    url: "https://pmjay.gov.in", tags: ["central", "health", "insurance", "income", "rural", "urban", "senior"],
    popularity: 96, year: 2018, criteria: {},
  },
  {
    id: "pmay", level: "central", stateKey: null,
    name: { en: "Pradhan Mantri Awas Yojana", hi: "प्रधानमंत्री आवास योजना" },
    desc: { en: "Help to build or buy a permanent (pucca) home.", hi: "पक्का घर बनाने या खरीदने में मदद।" },
    benefits: { en: "Construction grant in villages, and home-loan interest subsidy in towns and cities.", hi: "गाँवों में निर्माण अनुदान, और शहरों में गृह ऋण पर ब्याज सब्सिडी।" },
    eligibility: { en: "Households with no pucca house anywhere in India; income bands decide the benefit.", hi: "जिन परिवारों के पास भारत में कहीं पक्का घर नहीं; लाभ आय वर्ग के अनुसार।" },
    documents: docs(["Aadhaar", "Income certificate", "Bank passbook", "Property or land papers"], ["आधार", "आय प्रमाणपत्र", "बैंक पासबुक", "संपत्ति या ज़मीन के कागज़"]),
    url: "https://pmay-urban.gov.in", tags: ["central", "housing", "rural", "urban", "income"],
    popularity: 92, year: 2015, criteria: { minAge: 18 },
  },
  {
    id: "ujjwala", level: "central", stateKey: null,
    name: { en: "PM Ujjwala Yojana", hi: "पीएम उज्ज्वला योजना" },
    desc: { en: "Free cooking-gas connection in the name of a woman from a poor household.", hi: "गरीब परिवार की महिला के नाम पर मुफ़्त रसोई गैस कनेक्शन।" },
    benefits: { en: "LPG connection with no deposit, plus stove and first refill support.", hi: "बिना जमा राशि के एलपीजी कनेक्शन, साथ में चूल्हा और पहली रिफिल की सहायता।" },
    eligibility: { en: "Adult woman from a poor family with no existing LPG connection at home.", hi: "गरीब परिवार की वयस्क महिला, जिसके घर में पहले से एलपीजी कनेक्शन न हो।" },
    documents: docs(["Aadhaar", "Ration card", "Bank passbook", "Address proof"], ["आधार", "राशन कार्ड", "बैंक पासबुक", "पते का प्रमाण"]),
    url: "https://www.pmuy.gov.in", tags: ["central", "women", "income", "rural"],
    popularity: 90, year: 2016, criteria: { genders: ["female"], minAge: 18, incomes: ["bpl"] },
  },
  {
    id: "sukanya-samriddhi", level: "central", stateKey: null,
    name: { en: "Sukanya Samriddhi Yojana", hi: "सुकन्या समृद्धि योजना" },
    desc: { en: "High-interest, tax-free savings account for a daughter's future.", hi: "बेटी के भविष्य के लिए ऊँचे ब्याज वाला कर-मुक्त बचत खाता।" },
    benefits: { en: "Government-set interest rate, tax benefits, and maturity when the girl turns 21.", hi: "सरकार द्वारा तय ब्याज दर, कर लाभ, और बेटी के 21 वर्ष की होने पर परिपक्वता।" },
    eligibility: { en: "Parent or guardian of a girl under 10; up to two girls per family.", hi: "10 वर्ष से कम आयु की बेटी के माता-पिता या अभिभावक; प्रति परिवार दो बेटियों तक।" },
    documents: docs(["Girl's birth certificate", "Guardian's Aadhaar and PAN", "Address proof"], ["बेटी का जन्म प्रमाणपत्र", "अभिभावक का आधार और पैन", "पते का प्रमाण"]),
    url: "https://www.indiapost.gov.in", tags: ["central", "women", "education", "income"],
    popularity: 84, year: 2015, criteria: {},
  },
  {
    id: "nsp-scholarships", level: "central", stateKey: null,
    name: { en: "National Scholarship Portal", hi: "राष्ट्रीय छात्रवृत्ति पोर्टल" },
    desc: { en: "One portal for central pre-matric, post-matric and merit scholarships.", hi: "केंद्रीय प्री-मैट्रिक, पोस्ट-मैट्रिक और मेरिट छात्रवृत्तियों के लिए एक पोर्टल।" },
    benefits: { en: "Fee support and a maintenance allowance paid into the student's account.", hi: "फ़ीस सहायता और रखरखाव भत्ता सीधे छात्र के खाते में।" },
    eligibility: { en: "Students in recognised institutions from SC, ST, OBC, minority or low-income families.", hi: "मान्यता प्राप्त संस्थानों के SC, ST, OBC, अल्पसंख्यक या कम आय वाले परिवारों के छात्र।" },
    documents: docs(["Aadhaar", "Income certificate", "Caste or community certificate", "Previous marksheet", "Bank passbook"], ["आधार", "आय प्रमाणपत्र", "जाति या समुदाय प्रमाणपत्र", "पिछली अंकतालिका", "बैंक पासबुक"]),
    url: "https://scholarships.gov.in", tags: ["central", "education", "scholarship", "student", "sc", "st", "obc", "minority", "income"],
    popularity: 93, year: 2015, criteria: { occupations: ["student"], maxAge: 35, categories: ["sc", "st", "obc", "minority"] },
  },
  {
    id: "vidyalakshmi", level: "central", stateKey: null,
    name: { en: "PM Vidyalaxmi Education Loans", hi: "पीएम विद्यालक्ष्मी शिक्षा ऋण" },
    desc: { en: "Apply to many banks for an education loan through a single portal.", hi: "एक ही पोर्टल से कई बैंकों में शिक्षा ऋण के लिए आवेदन।" },
    benefits: { en: "Collateral-free loans for quality institutions, with interest help for lower-income families.", hi: "अच्छे संस्थानों के लिए बिना गारंटी ऋण, कम आय वाले परिवारों को ब्याज सहायता।" },
    eligibility: { en: "Students who have secured admission to a recognised higher-education course.", hi: "मान्यता प्राप्त उच्च शिक्षा पाठ्यक्रम में प्रवेश पा चुके छात्र।" },
    documents: docs(["Admission letter", "Marksheets", "Family income proof", "Aadhaar"], ["प्रवेश पत्र", "अंकतालिकाएँ", "पारिवारिक आय प्रमाण", "आधार"]),
    url: "https://pmvidyalaxmi.gov.in", tags: ["central", "education", "student"],
    popularity: 76, year: 2024, criteria: { occupations: ["student"], minAge: 17, maxAge: 35 },
  },
  {
    id: "mudra", level: "central", stateKey: null,
    name: { en: "PM MUDRA Yojana", hi: "पीएम मुद्रा योजना" },
    desc: { en: "Loans without collateral for small shops, services and micro-businesses.", hi: "छोटी दुकानों, सेवाओं और सूक्ष्म व्यवसायों के लिए बिना गारंटी ऋण।" },
    benefits: { en: "Loans up to ₹20 lakh across the Shishu, Kishor, Tarun and Tarun Plus tiers.", hi: "शिशु, किशोर, तरुण और तरुण प्लस श्रेणियों में ₹20 लाख तक का ऋण।" },
    eligibility: { en: "Individuals and micro-enterprises in non-farm income activities.", hi: "गैर-कृषि आय गतिविधियों वाले व्यक्ति और सूक्ष्म उद्यम।" },
    documents: docs(["Aadhaar", "PAN", "Business plan or quotation", "Bank statement"], ["आधार", "पैन", "व्यवसाय योजना या कोटेशन", "बैंक स्टेटमेंट"]),
    url: "https://www.mudra.org.in", tags: ["central", "business", "employment", "startup", "women", "urban", "rural"],
    popularity: 89, year: 2015, criteria: { occupations: ["business", "unemployed", "homemaker"], minAge: 18 },
  },
  {
    id: "stand-up-india", level: "central", stateKey: null,
    name: { en: "Stand-Up India", hi: "स्टैंड-अप इंडिया" },
    desc: { en: "Bank loans to help SC/ST and women founders start a new enterprise.", hi: "SC/ST और महिला उद्यमियों को नया उद्यम शुरू करने के लिए बैंक ऋण।" },
    benefits: { en: "Loans from ₹10 lakh to ₹1 crore for a first-time (greenfield) venture.", hi: "पहली बार (ग्रीनफ़ील्ड) उद्यम के लिए ₹10 लाख से ₹1 करोड़ तक ऋण।" },
    eligibility: { en: "SC, ST or woman entrepreneur aged 18+ starting a new manufacturing, services, trading or farm-allied unit.", hi: "18+ आयु के SC, ST या महिला उद्यमी जो नया विनिर्माण, सेवा, व्यापार या कृषि-संबद्ध उद्यम शुरू कर रहे हों।" },
    documents: docs(["Aadhaar", "Caste certificate (if SC/ST)", "Project report", "PAN"], ["आधार", "जाति प्रमाणपत्र (SC/ST हेतु)", "परियोजना रिपोर्ट", "पैन"]),
    url: "https://www.standupmitra.in", tags: ["central", "business", "startup", "women", "sc", "st", "employment"],
    popularity: 71, year: 2016, criteria: { minAge: 18, occupations: ["business", "unemployed", "employee", "homemaker"], categories: ["sc", "st"], groups: ["women"] },
  },
  {
    id: "pmkvy", level: "central", stateKey: null,
    name: { en: "PM Kaushal Vikas Yojana", hi: "पीएम कौशल विकास योजना" },
    desc: { en: "Free short-term job training with a government certificate.", hi: "सरकारी प्रमाणपत्र के साथ मुफ़्त अल्पकालिक रोज़गार प्रशिक्षण।" },
    benefits: { en: "Industry-linked training, assessment, certification and placement help at no cost.", hi: "उद्योग से जुड़ा प्रशिक्षण, मूल्यांकन, प्रमाणपत्र और नौकरी में सहायता, बिना शुल्क।" },
    eligibility: { en: "Indian youth aged 15–45, including school or college dropouts and the unemployed.", hi: "15–45 वर्ष के भारतीय युवा, पढ़ाई छोड़ चुके और बेरोज़गार भी।" },
    documents: docs(["Aadhaar", "Education certificate", "Bank passbook"], ["आधार", "शैक्षिक प्रमाणपत्र", "बैंक पासबुक"]),
    url: "https://www.pmkvyofficial.org", tags: ["central", "skill", "employment", "student", "urban", "rural"],
    popularity: 82, year: 2015, criteria: { minAge: 15, maxAge: 45, occupations: ["unemployed", "student", "homemaker", "employee"] },
  },
  {
    id: "atal-pension", level: "central", stateKey: null,
    name: { en: "Atal Pension Yojana", hi: "अटल पेंशन योजना" },
    desc: { en: "Small monthly savings now for a fixed pension after 60.", hi: "अभी छोटी मासिक बचत, 60 के बाद तय पेंशन।" },
    benefits: { en: "Guaranteed pension of ₹1,000–₹5,000 a month from age 60, based on contribution.", hi: "योगदान के अनुसार 60 वर्ष से ₹1,000–₹5,000 मासिक गारंटीड पेंशन।" },
    eligibility: { en: "Citizens aged 18–40 with a savings bank account who are not income-tax payers.", hi: "18–40 वर्ष के नागरिक जिनका बचत खाता हो और जो आयकरदाता न हों।" },
    documents: docs(["Aadhaar", "Savings account details", "Mobile number"], ["आधार", "बचत खाते का विवरण", "मोबाइल नंबर"]),
    url: "https://www.pfrda.org.in", tags: ["central", "pension", "employment", "income"],
    popularity: 80, year: 2015, criteria: { minAge: 18, maxAge: 40 },
  },
  {
    id: "ignoaps", level: "central", stateKey: null,
    name: { en: "Indira Gandhi National Old Age Pension", hi: "इंदिरा गांधी राष्ट्रीय वृद्धावस्था पेंशन" },
    desc: { en: "Monthly pension for elderly people from poor households.", hi: "गरीब परिवारों के बुज़ुर्गों के लिए मासिक पेंशन।" },
    benefits: { en: "₹200–₹500 a month from the centre; most states add a top-up.", hi: "केंद्र से ₹200–₹500 प्रति माह; अधिकांश राज्य अतिरिक्त राशि जोड़ते हैं।" },
    eligibility: { en: "People aged 60 or above from a below-poverty-line household.", hi: "गरीबी रेखा से नीचे के परिवार के 60 वर्ष या अधिक आयु के लोग।" },
    documents: docs(["Aadhaar", "Age proof", "BPL card", "Bank passbook"], ["आधार", "आयु प्रमाण", "बीपीएल कार्ड", "बैंक पासबुक"]),
    url: "https://nsap.nic.in", tags: ["central", "pension", "senior", "income", "rural"],
    popularity: 78, year: 2007, criteria: { minAge: 60, incomes: ["bpl"] },
  },
  {
    id: "pmjjby", level: "central", stateKey: null,
    name: { en: "PM Jeevan Jyoti Bima Yojana", hi: "पीएम जीवन ज्योति बीमा योजना" },
    desc: { en: "Low-cost life insurance renewed yearly through your bank.", hi: "बैंक के ज़रिए हर साल नवीनीकृत होने वाला सस्ता जीवन बीमा।" },
    benefits: { en: "₹2 lakh life cover for a premium of ₹436 a year.", hi: "₹436 सालाना प्रीमियम पर ₹2 लाख का जीवन बीमा।" },
    eligibility: { en: "Bank or post-office account holders aged 18–50.", hi: "18–50 वर्ष के बैंक या डाकघर खाताधारक।" },
    documents: docs(["Aadhaar", "Bank account", "Consent-cum-declaration form"], ["आधार", "बैंक खाता", "सहमति-सह-घोषणा फ़ॉर्म"]),
    url: "https://jansuraksha.gov.in", tags: ["central", "insurance", "income"],
    popularity: 81, year: 2015, criteria: { minAge: 18, maxAge: 50 },
  },
  {
    id: "pmsby", level: "central", stateKey: null,
    name: { en: "PM Suraksha Bima Yojana", hi: "पीएम सुरक्षा बीमा योजना" },
    desc: { en: "Accident insurance for just ₹20 a year.", hi: "सिर्फ़ ₹20 सालाना में दुर्घटना बीमा।" },
    benefits: { en: "₹2 lakh for accidental death or full disability, ₹1 lakh for partial disability.", hi: "दुर्घटना में मृत्यु या पूर्ण विकलांगता पर ₹2 लाख, आंशिक विकलांगता पर ₹1 लाख।" },
    eligibility: { en: "Bank or post-office account holders aged 18–70.", hi: "18–70 वर्ष के बैंक या डाकघर खाताधारक।" },
    documents: docs(["Aadhaar", "Bank account", "Enrolment form"], ["आधार", "बैंक खाता", "नामांकन फ़ॉर्म"]),
    url: "https://jansuraksha.gov.in", tags: ["central", "insurance", "income"],
    popularity: 79, year: 2015, criteria: { minAge: 18, maxAge: 70 },
  },
  {
    id: "adip", level: "central", stateKey: null,
    name: { en: "ADIP Scheme for Persons with Disabilities", hi: "दिव्यांगजनों के लिए एडीआईपी योजना" },
    desc: { en: "Free or subsidised aids like wheelchairs, hearing aids and artificial limbs.", hi: "व्हीलचेयर, श्रवण यंत्र और कृत्रिम अंग जैसे उपकरण मुफ़्त या रियायती दर पर।" },
    benefits: { en: "Assistive devices at no cost or partial cost depending on income.", hi: "आय के अनुसार सहायक उपकरण मुफ़्त या आंशिक कीमत पर।" },
    eligibility: { en: "Persons with 40% or more disability within the scheme's income limit.", hi: "योजना की आय सीमा के भीतर 40% या अधिक दिव्यांगता वाले व्यक्ति।" },
    documents: docs(["Disability certificate or UDID card", "Aadhaar", "Income certificate", "Photograph"], ["दिव्यांगता प्रमाणपत्र या UDID कार्ड", "आधार", "आय प्रमाणपत्र", "फोटो"]),
    url: "https://depwd.gov.in", tags: ["central", "disabled", "health", "income"],
    popularity: 64, year: 1981, criteria: { groups: ["disabled"] },
  },
  {
    id: "startup-india-seed", level: "central", stateKey: null,
    name: { en: "Startup India Seed Fund Scheme", hi: "स्टार्टअप इंडिया सीड फंड योजना" },
    desc: { en: "Early funding for young startups through approved incubators.", hi: "मान्य इनक्यूबेटरों के ज़रिए नए स्टार्टअप को शुरुआती फंडिंग।" },
    benefits: { en: "Up to ₹20 lakh grant for proof of concept and up to ₹50 lakh for market entry.", hi: "प्रूफ़ ऑफ़ कॉन्सेप्ट हेतु ₹20 लाख तक अनुदान और बाज़ार प्रवेश हेतु ₹50 लाख तक।" },
    eligibility: { en: "DPIIT-recognised startups incorporated within the last two years.", hi: "पिछले दो वर्षों में पंजीकृत DPIIT-मान्यता प्राप्त स्टार्टअप।" },
    documents: docs(["Certificate of incorporation", "DPIIT recognition", "Pitch deck", "PAN"], ["निगमन प्रमाणपत्र", "DPIIT मान्यता", "पिच डेक", "पैन"]),
    url: "https://seedfund.startupindia.gov.in", tags: ["central", "startup", "business", "employment", "urban"],
    popularity: 68, year: 2021, criteria: { minAge: 18, occupations: ["business", "employee", "student", "unemployed"] },
  },
  {
    id: "mgnrega", level: "central", stateKey: null,
    name: { en: "MGNREGA Rural Employment Guarantee", hi: "मनरेगा ग्रामीण रोज़गार गारंटी" },
    desc: { en: "Legal right to paid work for rural households.", hi: "ग्रामीण परिवारों को मज़दूरी वाले काम का कानूनी अधिकार।" },
    benefits: { en: "At least 100 days of wage work per household each financial year.", hi: "हर वित्तीय वर्ष में प्रति परिवार कम से कम 100 दिन का मज़दूरी वाला काम।" },
    eligibility: { en: "Adults in rural households who are willing to do unskilled manual work.", hi: "ग्रामीण परिवारों के वयस्क जो अकुशल शारीरिक काम करने को तैयार हों।" },
    documents: docs(["Job card", "Aadhaar", "Bank passbook", "Photograph"], ["जॉब कार्ड", "आधार", "बैंक पासबुक", "फोटो"]),
    url: "https://nrega.dord.gov.in", tags: ["central", "employment", "rural", "income"],
    popularity: 94, year: 2005, criteria: { minAge: 18, areas: ["rural"] },
  },
  {
    id: "ladli-behna-mp", level: "state", stateKey: "mp",
    name: { en: "Ladli Behna Yojana (Madhya Pradesh)", hi: "लाड़ली बहना योजना (मध्य प्रदेश)" },
    desc: { en: "Monthly cash support for women in Madhya Pradesh.", hi: "मध्य प्रदेश की महिलाओं को मासिक नकद सहायता।" },
    benefits: { en: "A fixed monthly amount paid to the woman's own bank account.", hi: "महिला के अपने बैंक खाते में तय मासिक राशि।" },
    eligibility: { en: "Women living in Madhya Pradesh, aged 21–60, from families that do not pay income tax.", hi: "मध्य प्रदेश में रहने वाली 21–60 वर्ष की महिलाएँ, जिनका परिवार आयकर नहीं देता।" },
    documents: docs(["Aadhaar", "Samagra ID", "Bank passbook", "Domicile proof"], ["आधार", "समग्र आईडी", "बैंक पासबुक", "मूल निवास प्रमाण"]),
    url: "https://cmladlibahna.mp.gov.in", tags: ["state", "women", "income"],
    popularity: 87, year: 2023, criteria: { states: ["mp"], genders: ["female"], minAge: 21, maxAge: 60 },
  },
  {
    id: "ladki-bahin-maharashtra", level: "state", stateKey: "maharashtra",
    name: { en: "Mukhyamantri Majhi Ladki Bahin (Maharashtra)", hi: "मुख्यमंत्री माझी लाडकी बहीण (महाराष्ट्र)" },
    desc: { en: "Monthly assistance for women in Maharashtra.", hi: "महाराष्ट्र की महिलाओं को मासिक सहायता।" },
    benefits: { en: "A monthly amount credited directly to the woman's account.", hi: "महिला के खाते में सीधे मासिक राशि।" },
    eligibility: { en: "Women resident in Maharashtra, aged 21–65, with family income under the state limit.", hi: "महाराष्ट्र निवासी 21–65 वर्ष की महिलाएँ, जिनकी पारिवारिक आय राज्य सीमा से कम हो।" },
    documents: docs(["Aadhaar", "Domicile certificate", "Income certificate", "Bank passbook"], ["आधार", "अधिवास प्रमाणपत्र", "आय प्रमाणपत्र", "बैंक पासबुक"]),
    url: "https://ladakibahin.maharashtra.gov.in", tags: ["state", "women", "income"],
    popularity: 86, year: 2024, criteria: { states: ["maharashtra"], genders: ["female"], minAge: 21, maxAge: 65 },
  },
  {
    id: "kanya-sumangala-up", level: "state", stateKey: "up",
    name: { en: "Mukhyamantri Kanya Sumangala (Uttar Pradesh)", hi: "मुख्यमंत्री कन्या सुमंगला (उत्तर प्रदेश)" },
    desc: { en: "Staged payments supporting a girl from birth through graduation.", hi: "जन्म से स्नातक तक बेटी की मदद के लिए चरणबद्ध भुगतान।" },
    benefits: { en: "Money released in six stages tied to birth, vaccination and schooling milestones.", hi: "जन्म, टीकाकरण और पढ़ाई के पड़ावों से जुड़े छह चरणों में राशि।" },
    eligibility: { en: "Girls from Uttar Pradesh families with annual income up to ₹3 lakh.", hi: "₹3 लाख तक वार्षिक आय वाले उत्तर प्रदेश के परिवारों की बेटियाँ।" },
    documents: docs(["Birth certificate", "Aadhaar", "Income certificate", "Bank passbook"], ["जन्म प्रमाणपत्र", "आधार", "आय प्रमाणपत्र", "बैंक पासबुक"]),
    url: "https://mksy.up.gov.in", tags: ["state", "women", "education", "scholarship", "student"],
    popularity: 74, year: 2019, criteria: { states: ["up"], genders: ["female"], maxAge: 25 },
  },
  {
    id: "maa-yojana-rajasthan", level: "state", stateKey: "rajasthan",
    name: { en: "Mukhyamantri Ayushman Arogya (MAA) Yojana (Rajasthan)", hi: "मुख्यमंत्री आयुष्मान आरोग्य (मा) योजना (राजस्थान)" },
    desc: { en: "Cashless health insurance for families in Rajasthan.", hi: "राजस्थान के परिवारों के लिए कैशलेस स्वास्थ्य बीमा।" },
    benefits: { en: "Large yearly cashless treatment cover at empanelled government and private hospitals.", hi: "सूचीबद्ध सरकारी और निजी अस्पतालों में बड़ा वार्षिक कैशलेस इलाज कवर।" },
    eligibility: { en: "Resident families of Rajasthan enrolled through Jan Aadhaar.", hi: "जन आधार के ज़रिए पंजीकृत राजस्थान के निवासी परिवार।" },
    documents: docs(["Jan Aadhaar card", "Aadhaar", "Address proof"], ["जन आधार कार्ड", "आधार", "पते का प्रमाण"]),
    url: "https://maayojana.rajasthan.gov.in", tags: ["state", "health", "insurance", "income"],
    popularity: 72, year: 2021, criteria: { states: ["rajasthan"] },
  },
  {
    id: "student-credit-card-bihar", level: "state", stateKey: "bihar",
    name: { en: "Bihar Student Credit Card", hi: "बिहार स्टूडेंट क्रेडिट कार्ड" },
    desc: { en: "Education loan for Bihar students going on to higher studies.", hi: "उच्च शिक्षा के लिए बिहार के छात्रों को शिक्षा ऋण।" },
    benefits: { en: "Loans up to ₹4 lakh at low interest, with lower rates for women, disabled and transgender students.", hi: "कम ब्याज पर ₹4 लाख तक ऋण; महिला, दिव्यांग और ट्रांसजेंडर छात्रों के लिए और कम दर।" },
    eligibility: { en: "Bihar residents who have passed class 12 and joined a recognised course.", hi: "12वीं पास बिहार निवासी जिन्होंने मान्यता प्राप्त पाठ्यक्रम में दाख़िला लिया हो।" },
    documents: docs(["Class 12 marksheet", "Admission letter", "Aadhaar", "Residence certificate"], ["12वीं की अंकतालिका", "प्रवेश पत्र", "आधार", "निवास प्रमाणपत्र"]),
    url: "https://www.7nishchay-yuvaupmission.bihar.gov.in", tags: ["state", "education", "student", "scholarship"],
    popularity: 70, year: 2016, criteria: { states: ["bihar"], occupations: ["student"], minAge: 17, maxAge: 25, educations: ["school", "graduate"] },
  },
];
